DROP TABLE IF EXISTS `bulten_veri`;

CREATE TABLE `bulten_veri` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `bltn_tarih` date NOT NULL,
  `bltn_macid` int(11) NOT NULL,
  `bltn_lig` varchar(255) DEFAULT NULL,
  `bltn_saat` time DEFAULT NULL,
  `bltn_mbs` double DEFAULT '4',
  `bltn_handikapiyev` double DEFAULT NULL,
  `bltn_handikapmsev` double DEFAULT NULL,
  `bltn_ev` varchar(200) DEFAULT NULL,
  `bltn_macsonucu1` double DEFAULT NULL,
  `bltn_macsonucu0` double DEFAULT NULL,
  `bltn_macsonucu2` double DEFAULT NULL,
  `bltn_konuk` varchar(200) DEFAULT NULL,
  `bltn_handikapiykonuk` double DEFAULT NULL,
  `bltn_handikapmskonuk` double DEFAULT NULL,
  `bltn_ciftsans10` double DEFAULT NULL,
  `bltn_ciftsans12` double DEFAULT NULL,
  `bltn_ciftcans20` double DEFAULT NULL,
  `bltn_handikap1` double DEFAULT NULL,
  `bltn_handikap0` double DEFAULT NULL,
  `bltn_handikap2` double DEFAULT NULL,
  `bltn_gol15alt` double DEFAULT NULL,
  `bltn_gol15ust` double DEFAULT NULL,
  `bltn_gol25alt` double DEFAULT NULL,
  `bltn_gol25ust` double DEFAULT NULL,
  `bltn_gol35alt` double DEFAULT NULL,
  `bltn_gol35ust` double DEFAULT NULL,
  `bltn_toplamsayi` double DEFAULT NULL,
  `bltn_kgvar` double DEFAULT NULL,
  `bltn_kgyok` double DEFAULT NULL,
  `bltn_toplamgol01` double DEFAULT NULL,
  `bltn_toplamgol23` double DEFAULT NULL,
  `bltn_toplamgol46` double DEFAULT NULL,
  `bltn_toplamgol7` double DEFAULT NULL,
  `bltn_ilkyarisonucu1` double DEFAULT NULL,
  `bltn_ilkyarisonucu0` double DEFAULT NULL,
  `bltn_ilkyarisonucu2` double DEFAULT NULL,
  `bltn_ilkyarisonucu15ust` double DEFAULT NULL,
  `bltn_ilkyarisonucu15alt` double DEFAULT NULL,
  `bltn_iymac11` double DEFAULT NULL,
  `bltn_iymac01` double DEFAULT NULL,
  `bltn_iymac21` double DEFAULT NULL,
  `bltn_iymac10` double DEFAULT NULL,
  `bltn_iymac00` double DEFAULT NULL,
  `bltn_iymac20` double DEFAULT NULL,
  `bltn_iymac12` double DEFAULT NULL,
  `bltn_iymac02` double DEFAULT NULL,
  `bltn_iymac22` double DEFAULT NULL,
  `bltn_benzersiz` varchar(55) DEFAULT NULL,
  `bltn_sinif` varchar(4) DEFAULT NULL,
  PRIMARY KEY (`ID`,`bltn_tarih`,`bltn_macid`),
  UNIQUE KEY `bltn_benzersiz_UNIQUE` (`bltn_benzersiz`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

